### ISSUE TITLE
Flow throws a permission denied in Linux

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.DockerFlow#1]
For Mac I added the guest user with id 1000 to the app container.
Maybe we need something similar for linux or that is actually the problem.

**Comment by visay** [comment]
We need to implement this as a post hook so that it can be executed independently by OS type.

**Comment by visay** [comment]
@Sebobo since you are building an image for docker hub, all users will always take that image with wrong uid for them. of course you can change the uid in dockerfile from 1000 to 1001 and adjust the fig to use local build rather than image from docker hub but it's not easy for long run.

Currently I don't know how to resolve that yet. I have tried to use the ONBUILD in dockerfile but this won't solve our problem with the existing image. I think I need to find out how to execute this command in fig. If you have any ideas, let me know. Would be good to solve this soon since more and more users from my team start using it.

**Comment by Sebobo** [comment]
I have some ideas and will take a look into this weekend.

**Comment by Sebobo** [comment]
@visay can you check out the work in progress `autocreate-user` branch and check if that works fine with your system?

**Comment by Sebobo** [comment]
Branch with changes merged, should work fine now :)
