### ISSUE TITLE
Upgrade from fig to to docker-compose

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.DockerFlow#14]

**Comment by visay** [comment]
Hi @Sebobo ,

Tested working like a charm. Thanks for that.

I merged the change and add a changelog for you https://github.com/Sebobo/Shel.DockerFlow/blob/master/CHANGELOG

I also set the image reference back to `sebobo/shel.dockerflow:latest` because I have set it to 0.0.1 in my previous commit for the tag

Now 2 workflow for the commit/merge request to be accepted:

1. Update documentation in README
2. Add release note in CHANGELOG
