### ISSUE TITLE
Check for docker and docker-compose when running dockerflow

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.DockerFlow#8]
Currently the wrapper will just throw errors if docker and fig are missing.
We should check that the binaries are there and fulfil a version requirement.

**Comment by Sebobo** [comment]
fig will be renamed to `docker-compose` soon: https://github.com/docker/fig/releases/tag/1.1.0-rc2

We need to adapt the wrapper and the configuration to that then (maybe have a fallback to the old way).

So checking for the installed package gets more important and to show a useful warning

**Comment by visay** [comment]
fig was not broadly used with dockerflow and i think we can forget about it and just keep it as historical. 

This means a check for docker and docker-compose should be enough for now and also I don't see a problem with version number yet. That's why I didn't detect the version in my commit 907af64b989644b3b7661aa33571451db61b67ce

Re-open the issue if you think that's not enough.
